-- Mock Data for Idaho Counties clues
-- This file contains sample data for testing and development

-- Insert sample users/authors (reuse existing user)
INSERT INTO "user" (id, first_name, last_name, email, native_lang, created_at) VALUES
('user_002', 'Ben', 'Zoon', 'ben_zoon@gmail.com', 'es', '2024-01-02 10:00:00')
ON CONFLICT (id) DO NOTHING;

-- Insert entries for all county names and capitals
INSERT INTO entry ("entry", root_entry, lang, "length", display_text, entry_type, familiarity_score, quality_score) VALUES
-- County names
('ADA', null, 'en', 3, 'Ada', 'word', null, null),
('ADAMS', null, 'en', 5, 'Adams', 'word', null, null),
('BANNOCK', null, 'en', 7, 'Bannock', 'word', null, null),
('BEARLAKE', null, 'en', 8, 'Bear Lake', 'word', null, null),
('BENEWAH', null, 'en', 7, 'Benewah', 'word', null, null),
('BINGHAM', null, 'en', 7, 'Bingham', 'word', null, null),
('BLAINE', null, 'en', 6, 'Blaine', 'word', null, null),
('BOISE', null, 'en', 5, 'Boise', 'word', null, null),
('BONNER', null, 'en', 6, 'Bonner', 'word', null, null),
('BONNEVILLE', null, 'en', 10, 'Bonneville', 'word', null, null),
('BOUNDARY', null, 'en', 8, 'Boundary', 'word', null, null),
('BUTTE', null, 'en', 5, 'Butte', 'word', null, null),
('CAMAS', null, 'en', 5, 'Camas', 'word', null, null),
('CANYON', null, 'en', 6, 'Canyon', 'word', null, null),
('CARIBOU', null, 'en', 7, 'Caribou', 'word', null, null),
('CASSIA', null, 'en', 6, 'Cassia', 'word', null, null),
('CLARK', null, 'en', 5, 'Clark', 'word', null, null),
('CLEARWATER', null, 'en', 10, 'Clearwater', 'word', null, null),
('CUSTER', null, 'en', 6, 'Custer', 'word', null, null),
('ELMORE', null, 'en', 6, 'Elmore', 'word', null, null),
('FRANKLIN', null, 'en', 8, 'Franklin', 'word', null, null),
('FREMONT', null, 'en', 7, 'Fremont', 'word', null, null),
('GEM', null, 'en', 3, 'Gem', 'word', null, null),
('GOODING', null, 'en', 7, 'Gooding', 'word', null, null),
('IDAHO', null, 'en', 5, 'Idaho', 'word', null, null),
('JEFFERSON', null, 'en', 9, 'Jefferson', 'word', null, null),
('JEROME', null, 'en', 6, 'Jerome', 'word', null, null),
('KOOTENAI', null, 'en', 8, 'Kootenai', 'word', null, null),
('LATAH', null, 'en', 5, 'Latah', 'word', null, null),
('LEMHI', null, 'en', 5, 'Lemhi', 'word', null, null),
('LEWIS', null, 'en', 5, 'Lewis', 'word', null, null),
('LINCOLN', null, 'en', 7, 'Lincoln', 'word', null, null),
('MADISON', null, 'en', 7, 'Madison', 'word', null, null),
('MINIDOKA', null, 'en', 8, 'Minidoka', 'word', null, null),
('NEZPERCE', null, 'en', 8, 'Nez Perce', 'word', null, null),
('ONEIDA', null, 'en', 6, 'Oneida', 'word', null, null),
('OWYHEE', null, 'en', 6, 'Owyhee', 'word', null, null),
('PAYETTE', null, 'en', 7, 'Payette', 'word', null, null),
('POWER', null, 'en', 5, 'Power', 'word', null, null),
('SHOSHONE', null, 'en', 8, 'Shoshone', 'word', null, null),
('TETON', null, 'en', 5, 'Teton', 'word', null, null),
('TWINFALLS', null, 'en', 9, 'Twin Falls', 'word', null, null),
('VALLEY', null, 'en', 6, 'Valley', 'word', null, null),
('WASHINGTON', null, 'en', 10, 'Washington', 'word', null, null),
-- County capitals
('BOISE', null, 'en', 5, 'Boise', 'word', null, null),
('COUNCIL', null, 'en', 7, 'Council', 'word', null, null),
('POCATELLO', null, 'en', 9, 'Pocatello', 'word', null, null),
('PARIS', null, 'en', 5, 'Paris', 'word', null, null),
('STMARIES', null, 'en', 8, 'St. Maries', 'word', null, null),
('BLACKFOOT', null, 'en', 9, 'Blackfoot', 'word', null, null),
('HAILEY', null, 'en', 6, 'Hailey', 'word', null, null),
('IDAHOCITY', null, 'en', 9, 'Idaho City', 'word', null, null),
('SANDPOINT', null, 'en', 9, 'Sandpoint', 'word', null, null),
('IDAHOFALLS', null, 'en', 10, 'Idaho Falls', 'word', null, null),
('BONNERSFERRY', null, 'en', 12, 'Bonners Ferry', 'word', null, null),
('ARCO', null, 'en', 4, 'Arco', 'word', null, null),
('FAIRFIELD', null, 'en', 9, 'Fairfield', 'word', null, null),
('CALDWELL', null, 'en', 8, 'Caldwell', 'word', null, null),
('SODASPRINGS', null, 'en', 11, 'Soda Springs', 'word', null, null),
('BURLEY', null, 'en', 6, 'Burley', 'word', null, null),
('DUBOIS', null, 'en', 6, 'Dubois', 'word', null, null),
('OROFINO', null, 'en', 7, 'Orofino', 'word', null, null),
('CHALLIS', null, 'en', 7, 'Challis', 'word', null, null),
('MOUNTAINHOME', null, 'en', 12, 'Mountain Home', 'word', null, null),
('PRESTON', null, 'en', 7, 'Preston', 'word', null, null),
('SAINTANTHONY', null, 'en', 12, 'Saint Anthony', 'word', null, null),
('EMMETT', null, 'en', 6, 'Emmett', 'word', null, null),
('GOODING', null, 'en', 7, 'Gooding', 'word', null, null),
('GRANGEVILLE', null, 'en', 11, 'Grangeville', 'word', null, null),
('RIGBY', null, 'en', 5, 'Rigby', 'word', null, null),
('JEROME', null, 'en', 6, 'Jerome', 'word', null, null),
('COEURDALENE', null, 'en', 12, 'Coeur d''Alene', 'word', null, null),
('MOSCOW', null, 'en', 6, 'Moscow', 'word', null, null),
('SALMON', null, 'en', 6, 'Salmon', 'word', null, null),
('NEZPERCE', null, 'en', 8, 'Nezperce', 'word', null, null),
('SHOSHONE', null, 'en', 8, 'Shoshone', 'word', null, null),
('REXBURG', null, 'en', 7, 'Rexburg', 'word', null, null),
('RUPERT', null, 'en', 6, 'Rupert', 'word', null, null),
('LEWISTON', null, 'en', 8, 'Lewiston', 'word', null, null),
('MALADCITY', null, 'en', 9, 'Malad City', 'word', null, null),
('MURPHY', null, 'en', 6, 'Murphy', 'word', null, null),
('PAYETTE', null, 'en', 7, 'Payette', 'word', null, null),
('AMERICANFALLS', null, 'en', 13, 'American Falls', 'word', null, null),
('WALLACE', null, 'en', 7, 'Wallace', 'word', null, null),
('DRIGGS', null, 'en', 6, 'Driggs', 'word', null, null),
('TWINFALLS', null, 'en', 9, 'Twin Falls', 'word', null, null),
('CASCADE', null, 'en', 7, 'Cascade', 'word', null, null),
('WEISER', null, 'en', 6, 'Weiser', 'word', null, null)
ON CONFLICT (entry, lang) DO NOTHING;

-- Insert clues (2 per county: county name -> capital, county code -> county name)
INSERT INTO clue (id, entry, lang, sense_id, custom_clue, custom_display_text, source) VALUES
-- County name -> Capital clues
('county_clue_001', 'BOISE', 'en', NULL, 'Ada', 'Boise', 'Cruzi'),
('county_clue_002', 'COUNCIL', 'en', NULL, 'Adams', 'Council', 'Cruzi'),
('county_clue_003', 'POCATELLO', 'en', NULL, 'Bannock', 'Pocatello', 'Cruzi'),
('county_clue_004', 'PARIS', 'en', NULL, 'Bear Lake', 'Paris', 'Cruzi'),
('county_clue_005', 'STMARIES', 'en', NULL, 'Benewah', 'St. Maries', 'Cruzi'),
('county_clue_006', 'BLACKFOOT', 'en', NULL, 'Bingham', 'Blackfoot', 'Cruzi'),
('county_clue_007', 'HAILEY', 'en', NULL, 'Blaine', 'Hailey', 'Cruzi'),
('county_clue_008', 'IDAHOCITY', 'en', NULL, 'Boise', 'Idaho City', 'Cruzi'),
('county_clue_009', 'SANDPOINT', 'en', NULL, 'Bonner', 'Sandpoint', 'Cruzi'),
('county_clue_010', 'IDAHOFALLS', 'en', NULL, 'Bonneville', 'Idaho Falls', 'Cruzi'),
('county_clue_011', 'BONNERSFERRY', 'en', NULL, 'Boundary', 'Bonners Ferry', 'Cruzi'),
('county_clue_012', 'ARCO', 'en', NULL, 'Butte', 'Arco', 'Cruzi'),
('county_clue_013', 'FAIRFIELD', 'en', NULL, 'Camas', 'Fairfield', 'Cruzi'),
('county_clue_014', 'CALDWELL', 'en', NULL, 'Canyon', 'Caldwell', 'Cruzi'),
('county_clue_015', 'SODASPRINGS', 'en', NULL, 'Caribou', 'Soda Springs', 'Cruzi'),
('county_clue_016', 'BURLEY', 'en', NULL, 'Cassia', 'Burley', 'Cruzi'),
('county_clue_017', 'DUBOIS', 'en', NULL, 'Clark', 'Dubois', 'Cruzi'),
('county_clue_018', 'OROFINO', 'en', NULL, 'Clearwater', 'Orofino', 'Cruzi'),
('county_clue_019', 'CHALLIS', 'en', NULL, 'Custer', 'Challis', 'Cruzi'),
('county_clue_020', 'MOUNTAINHOME', 'en', NULL, 'Elmore', 'Mountain Home', 'Cruzi'),
('county_clue_021', 'PRESTON', 'en', NULL, 'Franklin', 'Preston', 'Cruzi'),
('county_clue_022', 'SAINTANTHONY', 'en', NULL, 'Fremont', 'Saint Anthony', 'Cruzi'),
('county_clue_023', 'EMMETT', 'en', NULL, 'Gem', 'Emmett', 'Cruzi'),
('county_clue_024', 'GOODING', 'en', NULL, 'Gooding', 'Gooding', 'Cruzi'),
('county_clue_025', 'GRANGEVILLE', 'en', NULL, 'Idaho', 'Grangeville', 'Cruzi'),
('county_clue_026', 'RIGBY', 'en', NULL, 'Jefferson', 'Rigby', 'Cruzi'),
('county_clue_027', 'JEROME', 'en', NULL, 'Jerome', 'Jerome', 'Cruzi'),
('county_clue_028', 'COEURDALENE', 'en', NULL, 'Kootenai', 'Coeur d''Alene', 'Cruzi'),
('county_clue_029', 'MOSCOW', 'en', NULL, 'Latah', 'Moscow', 'Cruzi'),
('county_clue_030', 'SALMON', 'en', NULL, 'Lemhi', 'Salmon', 'Cruzi'),
('county_clue_031', 'NEZPERCE', 'en', NULL, 'Lewis', 'Nezperce', 'Cruzi'),
('county_clue_032', 'SHOSHONE', 'en', NULL, 'Lincoln', 'Shoshone', 'Cruzi'),
('county_clue_033', 'REXBURG', 'en', NULL, 'Madison', 'Rexburg', 'Cruzi'),
('county_clue_034', 'RUPERT', 'en', NULL, 'Minidoka', 'Rupert', 'Cruzi'),
('county_clue_035', 'LEWISTON', 'en', NULL, 'Nez Perce', 'Lewiston', 'Cruzi'),
('county_clue_036', 'MALADCITY', 'en', NULL, 'Oneida', 'Malad City', 'Cruzi'),
('county_clue_037', 'MURPHY', 'en', NULL, 'Owyhee', 'Murphy', 'Cruzi'),
('county_clue_038', 'PAYETTE', 'en', NULL, 'Payette', 'Payette', 'Cruzi'),
('county_clue_039', 'AMERICANFALLS', 'en', NULL, 'Power', 'American Falls', 'Cruzi'),
('county_clue_040', 'WALLACE', 'en', NULL, 'Shoshone', 'Wallace', 'Cruzi'),
('county_clue_041', 'DRIGGS', 'en', NULL, 'Teton', 'Driggs', 'Cruzi'),
('county_clue_042', 'TWINFALLS', 'en', NULL, 'Twin Falls', 'Twin Falls', 'Cruzi'),
('county_clue_043', 'CASCADE', 'en', NULL, 'Valley', 'Cascade', 'Cruzi'),
('county_clue_044', 'WEISER', 'en', NULL, 'Washington', 'Weiser', 'Cruzi'),
-- County code -> County name clues
('code_clue_001', 'ADA', 'en', NULL, '1A', 'Ada', 'Cruzi'),
('code_clue_002', 'ADAMS', 'en', NULL, '2A', 'Adams', 'Cruzi'),
('code_clue_003', 'BANNOCK', 'en', NULL, '1B', 'Bannock', 'Cruzi'),
('code_clue_004', 'BEARLAKE', 'en', NULL, '2B', 'Bear Lake', 'Cruzi'),
('code_clue_005', 'BENEWAH', 'en', NULL, '3B', 'Benewah', 'Cruzi'),
('code_clue_006', 'BINGHAM', 'en', NULL, '4B', 'Bingham', 'Cruzi'),
('code_clue_007', 'BLAINE', 'en', NULL, '5B', 'Blaine', 'Cruzi'),
('code_clue_008', 'BOISE', 'en', NULL, '6B', 'Boise', 'Cruzi'),
('code_clue_009', 'BONNER', 'en', NULL, '7B', 'Bonner', 'Cruzi'),
('code_clue_010', 'BONNEVILLE', 'en', NULL, '8B', 'Bonneville', 'Cruzi'),
('code_clue_011', 'BOUNDARY', 'en', NULL, '9B', 'Boundary', 'Cruzi'),
('code_clue_012', 'BUTTE', 'en', NULL, '10B', 'Butte', 'Cruzi'),
('code_clue_013', 'CAMAS', 'en', NULL, '1C', 'Camas', 'Cruzi'),
('code_clue_014', 'CANYON', 'en', NULL, '2C', 'Canyon', 'Cruzi'),
('code_clue_015', 'CARIBOU', 'en', NULL, '3C', 'Caribou', 'Cruzi'),
('code_clue_016', 'CASSIA', 'en', NULL, '4C', 'Cassia', 'Cruzi'),
('code_clue_017', 'CLARK', 'en', NULL, '5C', 'Clark', 'Cruzi'),
('code_clue_018', 'CLEARWATER', 'en', NULL, '6C', 'Clearwater', 'Cruzi'),
('code_clue_019', 'CUSTER', 'en', NULL, '7C', 'Custer', 'Cruzi'),
('code_clue_020', 'ELMORE', 'en', NULL, 'E', 'Elmore', 'Cruzi'),
('code_clue_021', 'FRANKLIN', 'en', NULL, '1F', 'Franklin', 'Cruzi'),
('code_clue_022', 'FREMONT', 'en', NULL, '2F', 'Fremont', 'Cruzi'),
('code_clue_023', 'GEM', 'en', NULL, '1G', 'Gem', 'Cruzi'),
('code_clue_024', 'GOODING', 'en', NULL, '2G', 'Gooding', 'Cruzi'),
('code_clue_025', 'IDAHO', 'en', NULL, 'I', 'Idaho', 'Cruzi'),
('code_clue_026', 'JEFFERSON', 'en', NULL, '1J', 'Jefferson', 'Cruzi'),
('code_clue_027', 'JEROME', 'en', NULL, '2J', 'Jerome', 'Cruzi'),
('code_clue_028', 'KOOTENAI', 'en', NULL, 'K', 'Kootenai', 'Cruzi'),
('code_clue_029', 'LATAH', 'en', NULL, '1L', 'Latah', 'Cruzi'),
('code_clue_030', 'LEMHI', 'en', NULL, '2L', 'Lemhi', 'Cruzi'),
('code_clue_031', 'LEWIS', 'en', NULL, '3L', 'Lewis', 'Cruzi'),
('code_clue_032', 'LINCOLN', 'en', NULL, '4L', 'Lincoln', 'Cruzi'),
('code_clue_033', 'MADISON', 'en', NULL, '1M', 'Madison', 'Cruzi'),
('code_clue_034', 'MINIDOKA', 'en', NULL, '2M', 'Minidoka', 'Cruzi'),
('code_clue_035', 'NEZPERCE', 'en', NULL, 'N', 'Nez Perce', 'Cruzi'),
('code_clue_036', 'ONEIDA', 'en', NULL, '1O', 'Oneida', 'Cruzi'),
('code_clue_037', 'OWYHEE', 'en', NULL, '2O', 'Owyhee', 'Cruzi'),
('code_clue_038', 'PAYETTE', 'en', NULL, '1P', 'Payette', 'Cruzi'),
('code_clue_039', 'POWER', 'en', NULL, '2P', 'Power', 'Cruzi'),
('code_clue_040', 'SHOSHONE', 'en', NULL, 'S', 'Shoshone', 'Cruzi'),
('code_clue_041', 'TETON', 'en', NULL, '1T', 'Teton', 'Cruzi'),
('code_clue_042', 'TWINFALLS', 'en', NULL, '2T', 'Twin Falls', 'Cruzi'),
('code_clue_043', 'VALLEY', 'en', NULL, 'V', 'Valley', 'Cruzi'),
('code_clue_044', 'WASHINGTON', 'en', NULL, 'W', 'Washington', 'Cruzi');

-- Insert sample clue collection for Idaho counties
INSERT INTO clue_collection (id, title, author, description, created_date, modified_date, is_private, metadata1, metadata2, creator_id, puzzle_id, clue_count) VALUES
('collection_counties', 'Idaho Counties', 'Cruzi', 'Learn about Idaho counties, their capitals, and codes.', '2024-01-16 15:00:00', '2024-01-16 15:00:00', false, NULL, NULL, 'user_001', null, 88);

-- Insert collection-clue relationships
INSERT INTO collection__clue (collection_id, clue_id, "order", metadata1, metadata2) VALUES
-- County name -> Capital clues (order 1-44)
('collection_counties', 'county_clue_001', 1, NULL, NULL),
('collection_counties', 'county_clue_002', 2, NULL, NULL),
('collection_counties', 'county_clue_003', 3, NULL, NULL),
('collection_counties', 'county_clue_004', 4, NULL, NULL),
('collection_counties', 'county_clue_005', 5, NULL, NULL),
('collection_counties', 'county_clue_006', 6, NULL, NULL),
('collection_counties', 'county_clue_007', 7, NULL, NULL),
('collection_counties', 'county_clue_008', 8, NULL, NULL),
('collection_counties', 'county_clue_009', 9, NULL, NULL),
('collection_counties', 'county_clue_010', 10, NULL, NULL),
('collection_counties', 'county_clue_011', 11, NULL, NULL),
('collection_counties', 'county_clue_012', 12, NULL, NULL),
('collection_counties', 'county_clue_013', 13, NULL, NULL),
('collection_counties', 'county_clue_014', 14, NULL, NULL),
('collection_counties', 'county_clue_015', 15, NULL, NULL),
('collection_counties', 'county_clue_016', 16, NULL, NULL),
('collection_counties', 'county_clue_017', 17, NULL, NULL),
('collection_counties', 'county_clue_018', 18, NULL, NULL),
('collection_counties', 'county_clue_019', 19, NULL, NULL),
('collection_counties', 'county_clue_020', 20, NULL, NULL),
('collection_counties', 'county_clue_021', 21, NULL, NULL),
('collection_counties', 'county_clue_022', 22, NULL, NULL),
('collection_counties', 'county_clue_023', 23, NULL, NULL),
('collection_counties', 'county_clue_024', 24, NULL, NULL),
('collection_counties', 'county_clue_025', 25, NULL, NULL),
('collection_counties', 'county_clue_026', 26, NULL, NULL),
('collection_counties', 'county_clue_027', 27, NULL, NULL),
('collection_counties', 'county_clue_028', 28, NULL, NULL),
('collection_counties', 'county_clue_029', 29, NULL, NULL),
('collection_counties', 'county_clue_030', 30, NULL, NULL),
('collection_counties', 'county_clue_031', 31, NULL, NULL),
('collection_counties', 'county_clue_032', 32, NULL, NULL),
('collection_counties', 'county_clue_033', 33, NULL, NULL),
('collection_counties', 'county_clue_034', 34, NULL, NULL),
('collection_counties', 'county_clue_035', 35, NULL, NULL),
('collection_counties', 'county_clue_036', 36, NULL, NULL),
('collection_counties', 'county_clue_037', 37, NULL, NULL),
('collection_counties', 'county_clue_038', 38, NULL, NULL),
('collection_counties', 'county_clue_039', 39, NULL, NULL),
('collection_counties', 'county_clue_040', 40, NULL, NULL),
('collection_counties', 'county_clue_041', 41, NULL, NULL),
('collection_counties', 'county_clue_042', 42, NULL, NULL),
('collection_counties', 'county_clue_043', 43, NULL, NULL),
('collection_counties', 'county_clue_044', 44, NULL, NULL),
-- County code -> County name clues (order 45-88)
('collection_counties', 'code_clue_001', 45, NULL, NULL),
('collection_counties', 'code_clue_002', 46, NULL, NULL),
('collection_counties', 'code_clue_003', 47, NULL, NULL),
('collection_counties', 'code_clue_004', 48, NULL, NULL),
('collection_counties', 'code_clue_005', 49, NULL, NULL),
('collection_counties', 'code_clue_006', 50, NULL, NULL),
('collection_counties', 'code_clue_007', 51, NULL, NULL),
('collection_counties', 'code_clue_008', 52, NULL, NULL),
('collection_counties', 'code_clue_009', 53, NULL, NULL),
('collection_counties', 'code_clue_010', 54, NULL, NULL),
('collection_counties', 'code_clue_011', 55, NULL, NULL),
('collection_counties', 'code_clue_012', 56, NULL, NULL),
('collection_counties', 'code_clue_013', 57, NULL, NULL),
('collection_counties', 'code_clue_014', 58, NULL, NULL),
('collection_counties', 'code_clue_015', 59, NULL, NULL),
('collection_counties', 'code_clue_016', 60, NULL, NULL),
('collection_counties', 'code_clue_017', 61, NULL, NULL),
('collection_counties', 'code_clue_018', 62, NULL, NULL),
('collection_counties', 'code_clue_019', 63, NULL, NULL),
('collection_counties', 'code_clue_020', 64, NULL, NULL),
('collection_counties', 'code_clue_021', 65, NULL, NULL),
('collection_counties', 'code_clue_022', 66, NULL, NULL),
('collection_counties', 'code_clue_023', 67, NULL, NULL),
('collection_counties', 'code_clue_024', 68, NULL, NULL),
('collection_counties', 'code_clue_025', 69, NULL, NULL),
('collection_counties', 'code_clue_026', 70, NULL, NULL),
('collection_counties', 'code_clue_027', 71, NULL, NULL),
('collection_counties', 'code_clue_028', 72, NULL, NULL),
('collection_counties', 'code_clue_029', 73, NULL, NULL),
('collection_counties', 'code_clue_030', 74, NULL, NULL),
('collection_counties', 'code_clue_031', 75, NULL, NULL),
('collection_counties', 'code_clue_032', 76, NULL, NULL),
('collection_counties', 'code_clue_033', 77, NULL, NULL),
('collection_counties', 'code_clue_034', 78, NULL, NULL),
('collection_counties', 'code_clue_035', 79, NULL, NULL),
('collection_counties', 'code_clue_036', 80, NULL, NULL),
('collection_counties', 'code_clue_037', 81, NULL, NULL),
('collection_counties', 'code_clue_038', 82, NULL, NULL),
('collection_counties', 'code_clue_039', 83, NULL, NULL),
('collection_counties', 'code_clue_040', 84, NULL, NULL),
('collection_counties', 'code_clue_041', 85, NULL, NULL),
('collection_counties', 'code_clue_042', 86, NULL, NULL),
('collection_counties', 'code_clue_043', 87, NULL, NULL),
('collection_counties', 'code_clue_044', 88, NULL, NULL);
